### ISSUE TITLE
[Addition] Universal Tweaks

### ISSUE THREAD

**Issue by xJon** [Radplay/ActuallyUsefulMods#4]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Universal Tweaks

### What is your mod's main version?

1.12.X

### What is your mod's type?

Bugfix

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/universal-tweaks

### What is your reasoning for including this mod?

The mod is designed to fit quite comfortably into lists like these :)

**Comment by Radplay** [comment]
Thanks for the suggestion. I'll add it at some point, but first I want to remake the "Bugfix", "Helpful" and "Improvements" categories the same way I did with "Performance"
