### ISSUE TITLE
[Correction] Lazydfu-agent

### ISSUE THREAD

**Issue by SAJewers** [Radplay/ActuallyUsefulMods#8]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Lazydfu-agent

### What section(s) of the list is this correction for?

Performance

### What version(s) does this correction apply to?

Other (Fabric)

### What needs correcting?

The curseforge link takes me to a 404/mod not found page. I'm not sure if there's a mistake in the link, or if the mod was removed from curseforge.

### Input relevant link(s) which can be used to verify the correction.

https://www.curseforge.com/minecraft/mc-mods/lazydfu-agent

**Comment by Radplay** [comment]
Thanks, fixed
